#include<stdio.h>
#include<unistd.h>
#include<syslog.h>
void main()
{

        openlog("have start obu", LOG_CONS | LOG_PID, 0);
        syslog(LOG_DEBUG,"This is a syslog test message generated by program\n");
        printf("log finish\n");
        closelog();
}
